### PR TITLE
Fix for supporting custom queue table name

### PR DESCRIPTION
**Pull request by grzegorz-aniol**
I hope it looks good as it's my first Python contribution :)

### CODE REVIEW

**Comment by polyrand** [comment]
Thanks, this looks great! I thought this feature was working, but it seems I still had to update those functions. And thanks for adding the test case too!

I'll try to test the PR and merge it between now and the weekend, then release a new version of the Python package.

**Comment by grzegorz-aniol** [comment]
Now I found I have to use queue name in the test, I will fix this

**Comment by polyrand** [comment]
Yes, I was running the test, and I was about to say that haha, good catch! Thank you!

**Comment by polyrand** [comment]
~The `test_prune` test has to be updated too, because it also (incorrectly) assumes that the table name is `Queue`.~ I saw it's already done

As an extra "real usage test", I modified one of the test functions to save each test to a different local file instead of using the in-memory database for all the tests. Then I checked that some databases had both tables in the schema. Something like this:


```diff
@pytest.fixture(scope="function", params=["_pop_transaction", "_pop_returning"])
def single_queue(request, queue_name) -> LiteQueue:

+   import os

+   _q = LiteQueue(f"{os.urandom(3).hex()}.db", queue_name=queue_name or "Queue")
-   _q = LiteQueue(":memory:", queue_name=queue_name or "Queue")

    if _q.get_sqlite_version() > 35:
        _q.pop = getattr(_q, request.param)

    return _q
```

Then I ran the tests, and checked the schemas of all the generated databases:

```sh
for file in *.db; do echo "$file"; sqlite3 "$file" ".schema" | grep "CREATE TABLE"; done
```

This is not needed for the PR, just a note for later reference.

**Review by polyrand — APPROVED** [review]
Looks good! Thanks for the contribution!

**Comment by polyrand** [comment]
Version 0.9 is now available on [PyPI](https://pypi.org/project/litequeue/) with the fixes from this PR. Thanks!

**Pull request merged**
